Repository omisego/android-sdk, pull requests merged in 2018-03, with the labels that each got.

#10 fix typo in user kdoc
  omisego-sdk/src/main/java/co/omisego/omisego/models/User.kt
Labels: invalid

#12 Add script to deploy the library package to maven repository
  build.gradle
  omisego-sdk/build.gradle
  omisego-sdk/proguard-rules.pro
Labels: enhancement

#11 Refactor security package
  AUTHORS
  omisego-sdk/src/main/java/co/omisego/omisego/security/KeyHolder.kt
  omisego-sdk/src/main/java/co/omisego/omisego/security/KeyManager.kt
  omisego-sdk/src/main/java/co/omisego/omisego/security/KeyManagerMarshmallow.kt
  omisego-sdk/src/main/java/co/omisego/omisego/security/KeyManagerPreMarshmallow.kt
  omisego-sdk/src/main/java/co/omisego/omisego/security/KeyManagerPreference.kt
  omisego-sdk/src/main/java/co/omisego/omisego/security/OMGKeyManager.kt
  omisego-sdk/src/main/java/co/omisego/omisego/security/RSACipher.kt
Labels: enhancement

#15 Fix the callback is running on the wrong thread
  README.md
  build.gradle
  omisego-sdk/build.gradle
  omisego-sdk/src/main/java/co/omisego/omisego/custom/retrofit2/adapter/OMGCallAdapter.kt
  omisego-sdk/src/main/java/co/omisego/omisego/custom/retrofit2/adapter/OMGCallAdapterFactory.kt
  omisego-sdk/src/main/java/co/omisego/omisego/custom/retrofit2/adapter/OMGCallbackWrapper.kt
  omisego-sdk/src/main/java/co/omisego/omisego/custom/retrofit2/adapter/OMGCaller.kt
  omisego-sdk/src/main/java/co/omisego/omisego/custom/retrofit2/executor/MainThreadExecutor.kt
  omisego-sdk/src/main/java/co/omisego/omisego/model/Balance.kt
  omisego-sdk/src/main/java/co/omisego/omisego/model/MintedToken.kt
  omisego-sdk/src/main/java/co/omisego/omisego/network/ewallet/EWalletClient.kt
  omisego-sdk/src/test/kotlin/co/omisego/omisego/OMGAPIClientTest.kt
  omisego-sdk/src/test/kotlin/co/omisego/omisego/custom/retrofit2/adapter/OMGCallbackWrapperTest.kt
  omisego-sdk/src/test/kotlin/co/omisego/omisego/custom/retrofit2/converter/OMGConverterFactoryTest.kt
  omisego-sdk/src/test/kotlin/co/omisego/omisego/model/BalanceTest.kt
  omisego-sdk/src/test/kotlin/co/omisego/omisego/network/ewallet/EWalletClientTest.kt
Labels: bug

#18 Fix encryption bug
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  omisego-sdk/src/main/java/co/omisego/omisego/security/KeyManagerMarshmallow.kt
  omisego-sdk/src/main/java/co/omisego/omisego/security/OMGKeyManager.kt
Labels: bug
